[project]
name = "ddns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5"
]

[dependency-groups]
dev = [
    "pip>=26.0.1",
]
